version: '3'
services:
  playground-web-db:
    image: mongo:4.2.2
    environment:
      MONGO_INITDB_DATABASE: oj-gallery-mongo-db
    ports:
      - 27017:27017
  playground-web-frontend:
    image: oj-gallery-web-frontend:latest
    environment:
      PORT: 3000
      REACT_APP_API_SERVER_URL: http://localhost:8080/
    ports:
      - 3000:3000
  playground-web-backend:
    image: oj-gallery-web-backend:latest
    environment:
      APPLICATION_PORT: 8080
      DATABASE_URL: mongodb://playground-web-db:27017/oj-gallery-mongo-db
      AUTH_SECRET: t4!5_!S_@_s3cR37_f0r_3ncrPt!n9_P@ssWoR6
      AUTH_TOKEN_EXPIRY: 7200000
    ports:
      - 8080:8080